import { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronRight, Coffee, Compass, ExternalLink, FileText, Globe2, Home, Layers, MapPin, Menu, Search, Sparkles, Timer, Upload, X } from 'lucide-react';
import { DEMO_TODAY as MOCK_TODAY, WEEK_START as MOCK_WEEK } from './data/mock';
import { getArchiveProvider } from './data/provider';
import type { ArchiveSnapshot, Entity, Post, SearchResult } from './data/types';

const menus=['Home','Explore','Search','Stories','Timeline','Map','Weekly','Archive'] as const;
type Page=typeof menus[number];
type Detail={kind:'farm'|'producer'|'country';id:string};
const icons=[Home,Compass,Search,Layers,Timer,Globe2,FileText,Bookmark];
const countryKo:Record<string,string>={Colombia:'콜롬비아','Costa Rica':'코스타리카',Guatemala:'과테말라',Ethiopia:'에티오피아'};
const provider=getArchiveProvider();
function Badge({kind,mock=true,generated=false,excerpt=false}:{kind:'ai'|'original'|'external';mock?:boolean;generated?:boolean;excerpt?:boolean}) {return <span className={`badge ${excerpt?'original':kind}`}>{kind==='ai'&&!excerpt?<Sparkles size={11}/>:kind==='original'||excerpt?<FileText size={11}/>:<Globe2 size={11}/>} {kind==='ai'?(mock?'AI 정리 · 예시':generated?'AI 정리 · 원문 확인':excerpt?'원문 발췌':'기존 요약 · 검토 필요'):kind==='original'?(mock?'원문 형식 · 예시':'보관 원문'):'외부자료 · 미연결'}</span>}
function Landscape({small=false}:{small?:boolean}) {return <svg className={small?'landscape small':'landscape'} viewBox="0 0 1000 550" preserveAspectRatio="xMidYMid slice" aria-label="커피 산지의 추상적인 산 풍경 일러스트" role="img"><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor="#cbd9d6"/><stop offset="1" stopColor="#edf0dc"/></linearGradient><linearGradient id="mount" x2="0" y2="1"><stop stopColor="#69897a"/><stop offset="1" stopColor="#284c3d"/></linearGradient></defs><rect width="1000" height="550" fill="url(#sky)"/><circle cx="735" cy="120" r="54" fill="#f5f1d8" opacity=".65"/><path d="M0 330L140 205 270 267 400 144 550 274 660 179 810 250 1000 128V550H0Z" fill="#9bb0a2"/><path d="M0 362L180 296 340 322 510 234 665 341 850 262 1000 312V550H0Z" fill="#79998a"/><path d="M0 420Q140 260 350 409T760 352T1000 380V550H0Z" fill="url(#mount)"/><path d="M500 550Q620 435 1000 397" fill="none" stroke="#acc2a0" strokeWidth="23" opacity=".6"/><g fill="none" stroke="#acc2a0" opacity=".18" strokeWidth="3"><path d="M-100 450Q180 325 460 550"/><path d="M-100 470Q180 345 420 550"/><path d="M-100 490Q180 365 380 550"/><path d="M-100 510Q180 385 340 550"/></g></svg>}
export default function App(){
 const [data,setData]=useState<ArchiveSnapshot|null>(null); const [page,setPage]=useState<Page>('Home');
 const [query,setQuery]=useState('');const [result,setResult]=useState<SearchResult>({posts:[],related:[],mode:'local-keyword'});
 const [visibleLimit,setVisibleLimit]=useState(24);
 const [country,setCountry]=useState('All');const [topic,setTopic]=useState('All');const [year,setYear]=useState(2026);
 const [detail,setDetail]=useState<Detail|null>(null);const [post,setPost]=useState<Post|null>(null);const [mobile,setMobile]=useState(false);
 const [saved,setSaved]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('pilhoon-saved')||'[]')}catch{return []}});
 const [importOpen,setImportOpen]=useState(false);const [notice,setNotice]=useState('');const [importName,setImportName]=useState('');
 useEffect(()=>{setVisibleLimit(24)},[page,country,topic,year,query]);
 useEffect(()=>{provider.getSnapshot().then(setData).catch(()=>setNotice('기존 기록을 불러오지 못했습니다. 네트워크를 확인하고 새로고침해 주세요.'))},[]);
 useEffect(()=>{if(!data)return;let active=true;provider.search(query,data.posts).then(r=>{if(active)setResult(r)});return()=>{active=false}},[query,data]);
 useEffect(()=>{try{localStorage.setItem('pilhoon-saved',JSON.stringify(saved))}catch{/* Browser storage can be unavailable. */}},[saved]);
 useEffect(()=>{
  if(!detail&&!post&&!importOpen)return;
  const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const trap=(e:KeyboardEvent)=>{
   if(e.key!=='Tab')return;
   const dialogs=document.querySelectorAll<HTMLElement>('[role="dialog"]');
   const dialog=dialogs[dialogs.length-1];if(!dialog)return;
   const controls=[...dialog.querySelectorAll<HTMLElement>('button,a[href],input,select,[tabindex="0"]')].filter(el=>el.getClientRects().length>0);
   const first=controls[0],last=controls.at(-1);if(!first||!last)return;
   if(e.shiftKey&&(document.activeElement===first||!dialog.contains(document.activeElement))){e.preventDefault();last.focus()}
   else if(!e.shiftKey&&(document.activeElement===last||!dialog.contains(document.activeElement))){e.preventDefault();first.focus()}
  };
  document.addEventListener('keydown',trap);
  return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',trap)};
 },[detail,post,importOpen]);
 const filtered=useMemo(()=>data?.posts.filter(p=>(country==='All'||p.country===country)&&(topic==='All'||p.tags.includes(topic))&&Number(p.date.slice(0,4))<=year).sort((a,b)=>b.date.localeCompare(a.date))||[],[data,country,topic,year]);
 const go=(p:Page)=>{setPage(p);setMobile(false);setDetail(null);setPost(null);window.scrollTo({top:0,behavior:'smooth'})};
 const search=(q:string)=>{setQuery(q);go('Search')};
 const toggleSave=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 if(!data)return <div className="loading"><Coffee/><p>{notice||'산지 기록을 펼치는 중…'}</p></div>;
 const isDemo=data.posts[0]?.isMock!==false;
 const DEMO_TODAY=isDemo?MOCK_TODAY:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const monday=new Date(DEMO_TODAY+'T00:00:00Z');monday.setUTCDate(monday.getUTCDate()-((monday.getUTCDay()+6)%7));
 const WEEK_START=isDemo?MOCK_WEEK:monday.toISOString().slice(0,10);
 const collection=data.collection;
 const minYear=isDemo?2018:2015;
 const latest=[...data.posts].sort((a,b)=>b.date.localeCompare(a.date))[0];
 const countries=[...new Set(data.posts.map(p=>p.country))].filter(c=>c!=='국가 미분류');
 const week=data.posts.filter(p=>p.date>=WEEK_START&&p.date<=DEMO_TODAY);
 const trending=Object.entries(week.flatMap(p=>p.tags).reduce<Record<string,number>>((acc,t)=>({...acc,[t]:(acc[t]||0)+1}),{})).sort((a,b)=>b[1]-a[1]).slice(0,6);
 const freshFarms=data.farms.filter(f=>!data.posts.some(p=>p.farmId===f.id&&p.date<WEEK_START));
 const freshPeople=data.producers.filter(f=>!data.posts.some(p=>p.producerId===f.id&&p.date<WEEK_START));
 const title:Record<Page,string>={Home:'커피의 이야기는, 연결됩니다.',Explore:'한 잔 너머의 세계.',Search:'궁금한 것부터 시작하세요.',Stories:'시간이 쌓이면 이야기가 됩니다.',Timeline:'기록을 따라, 시간을 거슬러.',Map:'커피가 자라는 곳.',Weekly:'이번 주, 우리가 배운 것.',Archive:'오래 남길 기록들.'};
 const subtitle:Record<Page,string>={Home:'산지의 작은 변화부터 생산자의 오래된 이야기까지.',Explore:'국가, 농장, 생산자와 주제로 기록을 탐색하세요.',Search:'같은 단어가 없어도, 관련된 이야기를 함께 찾아보세요.',Stories:'여러 해에 걸친 기록을 하나의 흐름으로 읽습니다.',Timeline:'타임머신으로 그해까지 쌓인 기록을 살펴보세요.',Map:'산지의 위치와 관련 기록을 함께 펼칩니다.',Weekly:`${WEEK_START} — ${DEMO_TODAY} · 주간 기록 상태`,Archive:'저장한 기록과 전체 원문 형식, 기존 데이터 가져오기.'};
 const cards=(posts:Post[],limit?:number)=><><div className="post-grid">{posts.slice(0,limit??visibleLimit).map(p=><article className="card post-card" key={p.id}>{p.imageUrl&&<button className="post-image-button" onClick={()=>setPost(p)} aria-label={`${p.title} 원문 보기`}><img className="post-image" src={p.imageUrl} loading="lazy" alt="기존 게시물에 보관된 사진"/></button>}<div className="post-top"><span className="eyebrow">{p.country} / {p.region}</span><button className={`icon-button ${saved.includes(p.id)?'is-saved':''}`} aria-label={saved.includes(p.id)?'저장 해제':'기록 저장'} onClick={()=>toggleSave(p.id)}><Bookmark size={17} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div><span className="eyebrow">{p.author&&`작성자 @${p.author}`}</span><Badge kind="ai" mock={isDemo} generated={p.summaryKind==='ai'} excerpt={p.summaryKind==='excerpt'}/><button className="text-button post-title" onClick={()=>setPost(p)}>{p.title}</button><p>{p.summary}</p><div className="tags">{p.tags.slice(0,3).map(t=><button key={t} onClick={()=>search(t)}>{t}</button>)}</div><footer><span>{p.date.replaceAll('-','.')}</span><button onClick={()=>setPost(p)}>근거 기록 <ArrowUpRight size={14}/></button></footer></article>)}</div>{!limit&&posts.length>visibleLimit&&<div className="load-more"><button className="soft-button" onClick={()=>setVisibleLimit(n=>n+24)}>기록 더 보기 · {Math.min(visibleLimit,posts.length)} / {posts.length}</button></div>}</>;
 const entityCards=(entities:Entity[],kind:'farm'|'producer')=><div className="entity-grid">{entities.map((e,i)=><button className="card entity-card" key={e.id} onClick={()=>setDetail({kind,id:e.id})}><div className={`entity-art tone-${i%4}`}><span>{kind==='farm'?<MapPin size={26}/>:<Coffee size={26}/>}</span><div className="art-lines"/></div><div className="entity-copy"><span className="eyebrow">{e.country} · {e.region}</span><h3>{e.name}</h3><p>{e.description}</p><span className="entity-meta">{data.posts.filter(p=>(kind==='farm'?p.farmId:p.producerId)===e.id).length}개 기록 <ArrowUpRight size={15}/></span></div></button>)}</div>;
 const filterBar=<div className="filter-bar"><label>국가 <select value={country} onChange={e=>setCountry(e.target.value)}><option value="All">전체 국가</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label>주제 <select value={topic} onChange={e=>setTopic(e.target.value)}><option value="All">전체 주제</option>{[...new Set(data.posts.flatMap(p=>p.tags))].sort().map(t=><option key={t}>{t}</option>)}</select></label><button className="soft-button" onClick={()=>{setCountry('All');setTopic('All');setYear(2026)}}>초기화</button><span className="muted">{filtered.length}개 기록</span></div>;
 const timeControl=<div className="card time-control"><div><span className="eyebrow">TIME MACHINE</span><h2>{year}<span>년까지의 기록</span></h2><p>선택한 연도 이후의 기록은 숨깁니다.</p></div><label className="slider"><span>{minYear} <strong>{year}</strong> 2026</span><input aria-label="타임머신 기준 연도" type="range" min={minYear} max="2026" value={year} onChange={e=>setYear(Number(e.target.value))}/></label></div>;
 const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='pilhoon-archive-snapshot.json';a.click();URL.revokeObjectURL(url)};
 const detailEntity=detail?.kind==='country'?null:detail? (detail.kind==='farm'?data.farms:data.producers).find(e=>e.id===detail.id):null;
 const detailPosts=detail?data.posts.filter(p=>(detail.kind==='country'?p.country===detail.id:detail.kind==='farm'?p.farmId===detail.id:p.producerId===detail.id)&&Number(p.date.slice(0,4))<=year).sort((a,b)=>a.date.localeCompare(b.date)):[];
 return <div className="app-shell">
 <aside className={`sidebar ${mobile?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('Home')}}><span className="brand-mark"><Coffee size={24}/></span><span>PILHOON<small>COFFEE ARCHIVE</small></span></a><div className="sidebar-label">YOUR COFFEE COMPANION</div><nav aria-label="주요 메뉴">{menus.map((m,i)=>{const Icon=icons[i];return <button key={m} className={page===m?'active':''} onClick={()=>go(m)}><Icon size={18}/>{m}{page===m&&<span className="nav-dot"/>}</button>})}</nav><div className="sidebar-bottom"><div className="mini-globe"><Globe2 size={24}/></div><p>From origin,<br/>with curiosity.</p><small>산지에서 시작되는 커피 공부</small><a href="https://www.instagram.com/libre_pil/" target="_blank" rel="noreferrer">@libre_pil <ArrowUpRight size={13}/></a><span className="demo-label">{isDemo?'독립 프로토타입 · MOCK DATA':collection?(collection.backfillComplete?'주간 수집 · 누락 기간 확인 완료':'주간 수집 · 누락 기록 보완 중'):'수집 미연결'}</span></div></aside>
 <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="메뉴 열기" onClick={()=>setMobile(!mobile)}><Menu size={21}/></button><span className="breadcrumb">Archive <ChevronRight size={13}/> <strong>{page}</strong></span><button className="top-search" onClick={()=>go('Search')}><Search size={16}/><span>기록 속에서 찾아보기</span><kbd>↵</kbd></button><span className="status-dot"/><span className="top-demo">{isDemo?'데모 · 2026.10.03':`마지막 기록 · ${latest.date}`}</span></header>
 <main><div className="page-head"><div><div className="eyebrow">{page==='Home'?'A LIVING JOURNAL OF COFFEE ORIGINS':`THE ARCHIVE / ${page.toUpperCase()}`}</div><h1>{title[page]}</h1><p>{subtitle[page]}</p></div><span className="edition">VOL. 01 <span>EARLY PREVIEW</span></span></div>
 <div className="demo-banner"><span><Sparkles size={14}/> {isDemo?'모든 인물·농장·게시물 내용은 기능 시연용 가상 데이터입니다. 서필훈 대표의 실제 기록이나 현재 위치가 아닙니다.':`기존 아카이브 ${data.posts.length.toLocaleString()}개를 연결했습니다. 마지막 보관 기록 ${latest.date} · 현재 위치와 최신 소식은 미확인 · 기존 분류와 요약은 검토가 필요합니다.`}</span></div>
 {page==='Home'&&isDemo&&<>
 <div className="home-hero"><section className="hero-landscape"><Landscape/><div className="hero-shade"/><div className="hero-content"><span className="glass-pill"><span className="live-dot"/> 현재 어디에 있나요? · 예시</span><h2>Colombia,<br/><em>in the field.</em></h2><p>Huila의 수확과 생산자의 선택을 따라.<br/>최근 방문 형식 기록: 2026.10.01</p><button className="white-button" onClick={()=>{setCountry('Colombia');go('Timeline')}}>방문 타임라인 보기 <ArrowRight size={16}/></button></div><span className="illustration-label">ORIGIN LANDSCAPE · ILLUSTRATION</span></section><section className="card hero-note"><div className="section-kicker"><Sparkles size={16}/> FIELD NOTES</div><h2>이번 주 산지에서<br/>나눈 이야기.</h2><Badge kind="ai" mock={isDemo}/><p>예시 기록에서는 우일라의 체리 선별, 타라주의 물 관리, 가족 농장의 다음 세대를 함께 살펴봅니다.</p><div className="note-stat"><strong>{week.length}</strong><span>이번 주 신규 기록<small>{WEEK_START.replaceAll('-','.')} — 10.03</small></span><ArrowUpRight size={22}/></div><button className="text-link" onClick={()=>go('Weekly')}>주간 브리핑 읽기 <ArrowRight size={15}/></button></section></div>
 <div className="stat-grid">{[[String(data.posts.length),'전체 기록','시간을 따라 쌓인 이야기'],[String(data.farms.length),'농장 아카이브','각자의 풍경과 선택'],[String(countries.length),'커피 생산국','한 잔을 잇는 산지'],[String(freshFarms.length),'이번 주 신규 농장','최초 등장 기준']].map(([v,l,h])=><div className="card stat-card" key={l}><span>{l}</span><strong>{v}<small>{l.includes('생산국')?'개국':'개'}</small></strong><p>{h}</p></div>)}</div>
 <Section title="최근 소식" subtitle="새 기록에서 발견한 작은 변화" action="모든 기록" onAction={()=>go('Explore')}/>{cards([...week].sort((a,b)=>b.date.localeCompare(a.date)),3)}
 <div className="two-col"><section className="card topic-card"><div className="section-kicker">TRENDING IN THE JOURNAL</div><h2>최근 자주 나눈 이야기</h2><p className="muted">이번 주 예시 게시물의 태그 빈도</p><div className="topic-list">{trending.map(([t,n],i)=><button key={t} onClick={()=>search(t)}><span className="rank">0{i+1}</span><strong>{t}</strong><span>{n}회</span><ArrowUpRight size={15}/></button>)}</div></section><section className="card connect-card"><span className="section-kicker"><Layers size={16}/> CONNECT THE DOTS</span><h2>비가 오면,<br/>커피는 어떻게 달라질까?</h2><p>강우 → 개화 → 수확 → 품질.<br/>여러 해의 기록을 연결해 하나의 주제를 깊게 읽어보세요.</p><div className="connection"><span>기후</span><i/><span>수확</span><i/><span>품질</span></div><button className="dark-button" onClick={()=>search('기후 수확')}>연결해서 보기 <ArrowRight size={15}/></button></section></div>
 <Section title="새로 만난 사람과 농장" subtitle="이번 주 처음 등장한 예시 기록"/>{entityCards(freshFarms,'farm')}<div className="people-strip">{freshPeople.map(p=><button className="card person" key={p.id} onClick={()=>setDetail({kind:'producer',id:p.id})}><span className="avatar">{p.name.slice(0,1)}</span><span><strong>{p.name}</strong><small>{p.country} · 신규 생산자</small></span><ArrowUpRight size={17}/></button>)}</div>
 <Section title="기록 밖의 세상" subtitle="외부 최신 정보 결합 · 연결 방식 예시"/>
 <div className="two-col">{data.issues.map(issue=><article className="card issue-card" key={issue.id}><Badge kind="external"/><h3>{issue.title}</h3><p>{issue.description}</p><small>발행일·검증일: 미연결</small><div className="issue-actions"><a href={issue.sourceUrl} target="_blank" rel="noreferrer">{issue.sourceLabel}<ExternalLink size={13}/></a><button onClick={()=>{setCountry(issue.country);go('Explore')}}>관련 기록 <ArrowRight size={13}/></button></div></article>)}</div>
 </>}
 {page==='Home'&&!isDemo&&<>
 <div className="home-hero"><section className="hero-landscape"><Landscape/><div className="hero-shade"/><div className="hero-content"><span className="glass-pill"><span className="live-dot"/> FROM THE ARCHIVE</span><h2>From origin,<br/><em>with curiosity.</em></h2><p>2015년부터 쌓인 산지와 커피의 이야기.<br/>기록을 연결하고, 원문에서 다시 배웁니다.</p><button className="white-button" onClick={()=>go('Explore')}>기록 탐색하기 <ArrowRight size={16}/></button></div><span className="illustration-label">ORIGIN LANDSCAPE · ILLUSTRATION</span></section><section className="card hero-note"><div className="section-kicker"><MapPin size={16}/> 현재 어디에 있나요?</div><h2>현재 방문지는<br/>확인되지 않았습니다.</h2><p>마지막 보관 기록은 {latest.date}입니다. 게시일만으로 현재 위치를 확정하지 않습니다.</p><div className="note-stat"><strong>{week.length}</strong><span>이번 주 날짜의 보관 기록<small>{WEEK_START} — {DEMO_TODAY}</small></span></div><button className="text-link" onClick={()=>go('Timeline')}>과거 기록 타임라인 <ArrowRight size={15}/></button></section></div>
 <div className="stat-grid">{[[String(data.posts.length),'전체 기록','원문 보존 · 새 사진은 원본 링크'],[String(data.farms.length),'농장 아카이브','기존 농장명 분류 연결'],[String(countries.length),'분류된 국가','기존 카테고리 기준'],[latest.date.slice(0,4),'최근 기록 연도','게시일 기준']].map(([v,l,h])=><div className="card stat-card" key={l}><span>{l}</span><strong>{v}</strong><p>{h}</p></div>)}</div>
 <Section title="최근 보관 기록" subtitle={`마지막 기록 ${latest.date} · 원본 링크에서 출처 확인`} action="모든 기록" onAction={()=>go('Explore')}/>{cards([...data.posts].sort((a,b)=>b.date.localeCompare(a.date)),3)}
 <div className="two-col"><section className="card topic-card"><div className="section-kicker">CONNECTED TOPICS</div><h2>이 주제를 어떻게 말해왔나?</h2><p className="muted">기록을 연결해 연도순으로 읽어보세요.</p><div className="topic-list">{['기후','가공','품종','핀카 리브레','인도','과테말라'].map((t,i)=><button key={t} onClick={()=>search(t)}><span className="rank">0{i+1}</span><strong>{t}</strong><ArrowUpRight size={15}/></button>)}</div></section><section className="card connect-card"><span className="section-kicker"><Layers size={16}/> CONNECT THE DOTS</span><h2>한 번의 방문을 넘어,<br/>여러 해의 이야기로.</h2><p>동일한 농장의 기록을 연도별로 모았습니다.<br/>기존 요약과 원문을 함께 확인하세요.</p><div className="connection"><span>농장</span><i/><span>시간</span><i/><span>기록</span></div><button className="dark-button" onClick={()=>go('Stories')}>연결해서 보기 <ArrowRight size={15}/></button></section></div>
 <Section title="농장의 오래된 이야기" subtitle="기존 분류의 농장 이름을 기준으로 연결 · 관계 검토 필요"/>{entityCards(data.farms,'farm')}
 <div className="two-col"><section className="card issue-card"><Badge kind="external"/><h3>외부 최신 정보 결합</h3><p>외부 관측·뉴스와 산지 기록을 연결하는 공간입니다. 아직 최신 정보 소스를 연결하지 않았습니다.</p></section><section className="card issue-card"><Badge kind="ai" mock={false}/><h3>이번 주 배운 것</h3><p>이번 주 날짜의 보관 기록은 {week.length}개입니다. 각 게시물의 원문과 요약을 함께 읽을 수 있습니다.</p><button className="text-link" onClick={()=>go('Weekly')}>주간 기록 상태 보기 <ArrowRight size={14}/></button></section></div>
 </>}
 {(page==='Explore'||page==='Stories')&&<>
 <Section title="국가에서 시작하기" subtitle="COUNTRIES & CONNECTIONS"/><div className="country-grid">{countries.map((c,i)=><button className="card country-card" key={c} onClick={()=>setDetail({kind:'country',id:c})}><span className="country-number">0{i+1}</span><Globe2 size={25}/><h3>{c}</h3><p>{countryKo[c]}</p><small>{data.posts.filter(p=>p.country===c).length}개 기록 <ArrowUpRight size={14}/></small></button>)}</div>
 <Section title="농장의 이야기" subtitle="여러 게시물로 읽는 하나의 농장"/>{entityCards(data.farms,'farm')}
 <Section title="생산자의 이야기" subtitle="사람을 중심으로 다시 연결하기"/>{data.producers.length?entityCards(data.producers,'producer'):<Empty message="기존 데이터에는 검증된 생산자별 분류가 없습니다. 원문에서 관계를 확인한 후 연결할 수 있습니다."/>}
 {page==='Explore'&&<><Section title="전체 기록 탐색" subtitle="국가와 주제를 조합해 찾아보세요"/>{filterBar}{filtered.length?cards(filtered):<Empty/>}</>}
 {page==='Stories'&&<section className="card story-feature"><Badge kind="ai" mock={isDemo}/><h2>이 주제를 어떻게 말해왔나?</h2><p>가공 방법의 관찰에서 기후와 건조의 관계까지. 주제별 검색으로 여러 해의 기록을 함께 읽어보세요.</p><div className="tags">{['기후','가공','Pink Bourbon','생산자'].map(t=><button key={t} onClick={()=>search(t)}>{t} <ArrowUpRight size={12}/></button>)}</div></section>}
 </>}
 {page==='Search'&&<><form className="search-box card" onSubmit={e=>e.preventDefault()}><Search size={25}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 기후 때문에 수확이 어려웠던 농장" aria-label="자연어 검색"/>{query&&<button type="button" className="icon-button" onClick={()=>setQuery('')} aria-label="검색어 지우기"><X size={19}/></button>}<button className="dark-button" type="submit">찾기 <ArrowRight size={16}/></button></form><p className="search-explanation">로컬 동의어·키워드 확장 데모입니다. 여러 조건은 관련도순으로 함께 검색되며, 실제 임베딩이나 AI 답변 생성은 연결되지 않았습니다.</p><div className="tags related"><span>관련 검색어</span>{result.related.map(t=><button key={t} onClick={()=>setQuery(t)}>{t}</button>)}</div>{query&&result.posts.length>0&&<div className="card search-summary"><Badge kind="ai" mock={isDemo}/><h2>이 기록들을 연결해서 읽어보세요.</h2><p>{[...new Set(result.posts.map(p=>p.region))].join(' · ')} 지역의 관련 기록 {result.posts.length}개를 찾았습니다. 각 카드에서 예시 근거를 확인할 수 있습니다.</p></div>}<Section title={query?`관련 기록 ${result.posts.length}개`:'추천 기록'} subtitle="연결된 농장·생산자 정보는 각 기록에서 확인하세요"/>{result.posts.length?cards(result.posts):<Empty/>}<Section title="이 주제를 어떻게 말해왔나?" subtitle="검색 결과를 연도순으로 읽기"/><div className="timeline">{[...result.posts].sort((a,b)=>a.date.localeCompare(b.date)).map(p=><TimelineItem key={p.id} post={p} onClick={()=>setPost(p)}/>)}</div></>}
 {page==='Timeline'&&<>{timeControl}{filterBar}<div className="timeline">{filtered.length?[...filtered].reverse().map(p=><TimelineItem key={p.id} post={p} onClick={()=>setPost(p)}/>):<Empty/>}</div></>}
 {page==='Map'&&<><div className="card map-panel"><div className="map-caption"><span className="eyebrow">ORIGIN ATLAS</span><h2>서로 다른 땅, 연결된 이야기.</h2><p>국가별 개략 위치 · 농장 좌표는 미연결</p></div><svg viewBox="0 0 1000 460" className="world-map" aria-label="중남미와 동아프리카의 커피 생산국 개략 지도"><defs><pattern id="grid" width="45" height="45" patternUnits="userSpaceOnUse"><path d="M45 0H0V45" fill="none" stroke="#d8e2db" strokeWidth=".7"/></pattern></defs><rect width="1000" height="460" fill="url(#grid)"/><g fill="#c7d7cc" stroke="#eef3ee" strokeWidth="2"><path d="M70 50L180 30 280 70 340 120 295 165 245 190 200 160 175 220 145 185 100 150Z"/><path d="M250 200L300 218 340 268 325 332 275 416 250 370 222 282 225 235Z"/><path d="M420 72L450 58 470 90 500 100 500 143 450 153 415 112Z"/><path d="M444 150L535 150 578 225 555 315 515 340 478 290 436 220Z"/><path d="M495 73L620 38 775 70 870 130 814 200 740 188 692 252 656 200 590 190 554 130Z"/><path d="M769 308L860 294 920 347 868 380 789 370Z"/><path d="M300 20L361 12 380 68 337 100Z"/></g>{[{c:'Guatemala',x:199,y:200},{c:'Costa Rica',x:220,y:222},{c:'Colombia',x:251,y:250},{c:'Ethiopia',x:560,y:230},{c:'India',x:675,y:200},{c:'Nicaragua',x:213,y:212},{c:'Honduras',x:209,y:203},{c:'Kenya',x:552,y:259},{c:'Panama',x:234,y:231}].filter(point=>countries.includes(point.c)).map(({c,x,y})=><g className="map-pin" key={c} role="button" tabIndex={0} aria-label={`${c} 기록 보기`} onClick={()=>setDetail({kind:'country',id:c})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setDetail({kind:'country',id:c})}}}><circle cx={x} cy={y} r="15" fill="#4f7962" opacity=".15"/><circle cx={x} cy={y} r="6" fill="#365944" stroke="white" strokeWidth="2"/><text x={x+20} y={y+5}>{c}</text></g>)}</svg><small>도식 지도 · 정확한 경계나 위치를 나타내는 지도는 아닙니다.</small></div><Section title="지도에서 기록으로" subtitle="국가를 선택하면 연도별 통합 요약을 볼 수 있습니다"/><div className="country-grid">{countries.map(c=><button className="card country-card" key={c} onClick={()=>setDetail({kind:'country',id:c})}><MapPin size={23}/><h3>{c}</h3><p>{countryKo[c]}</p><small>연결된 이야기 보기 <ArrowRight size={14}/></small></button>)}</div></>}
 {page==='Weekly'&&isDemo&&<><section className="weekly-hero card"><span className="section-kicker">THE WEEKLY / 001</span><h2>커피를 배우는<br/>조금 더 넓은 시선.</h2><Badge kind="ai" mock={isDemo}/><p>체리의 선별, 건조의 균일함, 다음 세대의 토양 관리.<br/>이번 주 예시 기록의 핵심을 모았습니다.</p><div className="weekly-numbers"><span><strong>{week.length}</strong> 신규 기록</span><span><strong>{freshFarms.length}</strong> 신규 농장</span><span><strong>{freshPeople.length}</strong> 신규 생산자</span></div></section><Section title="이번 주 배운 것" subtitle="요약과 근거를 함께 읽으세요"/><div className="two-col">{[{title:'01 · 품질은 수확에서 시작된다',id:'p06',text:'선별 기준과 수확 간격은 생산자의 중요한 선택이다.'},{title:'02 · 건조는 함께 관리하는 과정',id:'p12',text:'체리의 층 두께와 균일한 건조를 함께 살펴볼 수 있다.'}].map(n=><section className="card lesson" key={n.id}><Badge kind="ai" mock={isDemo}/><h3>{n.title}</h3><p>{n.text}</p><button className="text-link" onClick={()=>setPost(data.posts.find(p=>p.id===n.id)!)}>예시 근거 보기 <ArrowUpRight size={15}/></button></section>)}</div><Section title="이번 주의 모든 기록" subtitle="예시 기간 내 게시물"/>{cards(week)}<div className="card automation-note"><Timer size={24}/><div><h3>매주 새로운 이야기가 도착하도록.</h3><p>주간 브리핑 자동화 연결 예정 · 현재 예약 작업과 실제 알림은 설정되어 있지 않습니다.</p></div></div></>}
 {page==='Weekly'&&!isDemo&&<><section className="weekly-hero card"><span className="section-kicker">WEEKLY STATUS</span><h2>{week.length?"이번 주의 새로운 기록.":"새 기록을 기다리는 중."}</h2><p>{WEEK_START} — {DEMO_TODAY} 날짜의 보관 기록은 {week.length}개입니다.<br/>마지막 기록: {latest.date}. {collection?`${collection.schedule}. 최근 확인: ${collection.checkedAt}.`:"수집·알림 자동화는 아직 연결하지 않았습니다."}</p></section><Section title="이번 주 기록" subtitle="게시일 기준 · 신규 수집 여부를 나타내지 않습니다"/>{week.length?cards(week):<Empty message="이번 주 날짜의 보관 기록이 없습니다. Archive에서 기존 기록을 탐색해 보세요."/>}<Section title="대신, 최근 기록에서 읽기" subtitle="기존 요약과 실제 원본 링크"/>{cards([...data.posts].sort((a,b)=>b.date.localeCompare(a.date)),3)}</>}
 {page==='Archive'&&<><div className="two-col"><section className="card import-card"><Upload size={26}/><h2>오래된 기록도,<br/>이곳에서 다시 연결.</h2><p>4K Stogram의 캡션·사진·날짜를 가져오는 확장 지점입니다. 현재는 파일 선택과 안내만 지원합니다.</p><button className="dark-button" onClick={()=>setImportOpen(true)}>기존 데이터 가져오기 <ArrowRight size={15}/></button></section><section className="card import-card"><ArrowDownToLine size={26}/><h2>데이터를<br/>열린 형태로.</h2><p>현재 보관 데이터와 분류 구조를 JSON으로 내려받아 확인할 수 있습니다.</p><button className="soft-button" onClick={exportData}>기록 데이터 내보내기 <ArrowDownToLine size={15}/></button></section></div><Section title={`저장한 기록 ${saved.length}개`} subtitle="이 브라우저에 저장됩니다"/>{saved.length?cards(data.posts.filter(p=>saved.includes(p.id))):<Empty message="카드의 북마크를 누르면 여기에 모입니다."/>}<Section title="원문 형식 아카이브" subtitle="{isDemo?'아래 내용은 모두 시연용 가상 캡션입니다':'기존 사진·캡션·원본 링크를 보존했습니다'}"/>{filterBar}{cards(filtered)}</>}
 {collection&&<section className="card issue-card"><span className="section-kicker">COLLECTION STATUS</span><h3>주간 수집 상태</h3><p>{collection.schedule} · 최근 확인 {collection.checkedAt}</p><p>{collection.backfillComplete?"1월 말 이후의 누락 기록 확인을 마쳤습니다.":"2026년 1월 28일 이후의 누락 기록을 회차별로 채우는 중입니다. 전체 수집 완료 상태가 아닙니다."}</p><small>사진이 없는 새 기록은 원본 링크에서 사진을 확인하세요.</small></section>}<footer className="site-footer"><span>PILHOON COFFEE ARCHIVE</span><p>Observe. Connect. Understand.</p><small>{collection?"독립 아카이브 · 주간 브라우저 수집":"독립 아카이브 · Instagram 자동수집 미연결"}</small></footer>
 </main></div>
 {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal entity-modal" role="dialog" aria-modal="true" aria-label="통합 이야기" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setDetail(null)}}><button autoFocus className="close-button icon-button" onClick={()=>setDetail(null)} aria-label="닫기"><X/></button><span className="eyebrow">{detail.kind==='farm'?'FARM STORY':detail.kind==='producer'?'PRODUCER STORY':'COUNTRY STORY'}</span><h2>{detailEntity?.name||detail.id}</h2><p>{detailEntity?`${detailEntity.country} · ${detailEntity.region}`:countryKo[detail.id]}{detailEntity?.elevation&&` · ${detailEntity.elevation}`}</p><Badge kind="ai" mock={isDemo}/><p className="detail-description">{detailEntity?.description||'국가별 보관 기록을 연도순으로 연결합니다.'}</p>{timeControl}<div className="detail-stats"><span>관련 기록 <strong>{detailPosts.length}</strong></span><span>최초 등장 <strong>{detailPosts[0]?.date.slice(0,4)||'—'}</strong></span><span>최근 기록 <strong>{detailPosts.at(-1)?.date||'—'}</strong></span></div><h3>연도별 통합 이야기</h3><div className="timeline">{[...new Set(detailPosts.map(p=>p.date.slice(0,4)))].map(y=><div className="timeline-item" key={y}><span className="timeline-date">{y}</span><div><h3>{y} · {detailPosts.filter(p=>p.date.startsWith(y)).length}개 기록</h3><p>{detailPosts.filter(p=>p.date.startsWith(y)).slice(0,3).map(p=>p.summary).join(' ')}</p><small className="muted">해당 연도의 처음 3개 요약과 근거를 표시합니다.</small>{detailPosts.filter(p=>p.date.startsWith(y)).slice(0,3).map(p=><button className="evidence-link" key={p.id} onClick={()=>setPost(p)}><FileText size={13}/> 근거 {p.date} · {p.title} <ArrowUpRight size={12}/></button>)}</div></div>)}</div>{!detailPosts.length&&<Empty/>}<h3>연결해서 보기</h3><div className="tags">{[...new Set(detailPosts.flatMap(p=>p.tags))].slice(0,8).map(t=><button key={t} onClick={()=>search(t)}>{t}</button>)}</div></section></div>}
 {post&&<div className="modal-backdrop post-backdrop" onClick={()=>setPost(null)}><section className="modal post-modal" role="dialog" aria-modal="true" aria-label="근거 기록" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setPost(null)}}><button autoFocus className="close-button icon-button" onClick={()=>setPost(null)} aria-label="닫기"><X/></button><span className="eyebrow">{post.country} · {post.region} / {post.date} {post.author&&`· 작성자 @${post.author}`}</span><h2>{post.title}</h2>{post.imageUrl&&<img className="detail-image" src={post.imageUrl} alt="기존 게시물에 보관된 사진"/>}<div className="evidence-block original-block"><Badge kind="original" mock={post.isMock}/><p>{post.caption}</p><small>{post.isMock?'가상 캡션 · 서필훈 대표의 실제 발언이 아닙니다.':post.publishedAt?'로그인 브라우저에서 확인한 공개 캡션 · 게시일은 한국 시간 기준':'기존 아카이브에서 보관한 캡션 · 원본 링크에서 확인하세요.'}</small></div><div className={`evidence-block ${post.summaryKind==='excerpt'?'original-block':'ai-block'}`}><Badge kind="ai" mock={isDemo} generated={post.summaryKind==='ai'} excerpt={post.summaryKind==='excerpt'}/><p>{post.summary}</p><small>{post.isMock?'요약 표시를 위한 예시 텍스트 · 실제 모델 분석 미연결':post.summaryKind==='ai'?'수집한 원문을 AI가 정리했습니다. 해석과 분류는 원문에서 확인하세요.':post.summaryKind==='excerpt'?'원문 앞부분을 발췌했습니다. 자동 키워드 분류는 검토가 필요합니다.':'기존 아카이브의 요약을 보존했습니다. 새 AI 분석은 수행하지 않았습니다.'}</small></div><div className="tags">{post.tags.map(t=><button key={t} onClick={()=>search(t)}>{t}</button>)}</div><div className="post-entities">{post.farmId&&<button className="soft-button" onClick={()=>{setDetail({kind:'farm',id:post.farmId});setPost(null)}}>농장 이야기 <ArrowRight size={14}/></button>}{post.producerId&&<button className="soft-button" onClick={()=>{setDetail({kind:'producer',id:post.producerId});setPost(null)}}>생산자 이야기 <ArrowRight size={14}/></button>}<button className="soft-button" onClick={()=>toggleSave(post.id)}>{saved.includes(post.id)?<Check size={14}/>:<Bookmark size={14}/>} {saved.includes(post.id)?'저장됨':'저장하기'}</button></div>{post.sourceUrl?<a className="text-link" href={post.sourceUrl} target="_blank" rel="noreferrer">Instagram 원본 게시물 <ExternalLink size={14}/></a>:<p className="source-placeholder">예시 기록에는 실제 게시물 URL이 없습니다. 수집 연결 후 게시물별 원본 링크를 표시합니다.</p>}</section></div>}
 {importOpen&&<div className="modal-backdrop" onClick={()=>setImportOpen(false)}><section className="modal import-modal" role="dialog" aria-modal="true" aria-label="데이터 가져오기 안내" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setImportOpen(false)}}><button autoFocus className="close-button icon-button" onClick={()=>setImportOpen(false)} aria-label="닫기"><X/></button><Upload size={28}/><h2>4K Stogram import</h2><p>기존 내보내기 샘플을 선택해 파일명을 확인하는 placeholder입니다. 업로드·파싱·기록 추가는 수행하지 않습니다.</p><label className="file-drop">JSON / CSV 샘플 선택<input type="file" accept=".json,.csv" onChange={e=>setImportName(e.target.files?.[0]?.name||'')}/></label>{importName&&<div className="selected-file"><Check size={16}/>{importName} · 선택 완료, 변환 미연결</div>}<h3>향후 변환 필드</h3><p className="mono">id · date · caption · sourceUrl · localMediaPaths</p><p>날짜와 원본 URL을 검증한 뒤 미리보기 → 중복 제거 → 가져오기 순서로 연결합니다. 파일은 이 브라우저에서 선택만 되며 서버로 전송되지 않습니다.</p></section></div>}
 </div>
}
function Section({title,subtitle,action,onAction}:{title:string;subtitle:string;action?:string;onAction?:()=>void}){return <div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button className="text-link" onClick={onAction}>{action} <ArrowRight size={15}/></button>}</div>}
function Empty({message='조건에 맞는 기록이 없습니다. 다른 검색어나 필터를 사용해 보세요.'}:{message?:string}){return <div className="card empty"><Search size={24}/><p>{message}</p></div>}
function TimelineItem({post,onClick}:{post:Post;onClick:()=>void}){return <div className="timeline-item"><span className="timeline-date">{post.date.replaceAll('-','.')}</span><button className="timeline-content" onClick={onClick}><span className="eyebrow">{post.country} · {post.region}</span><h3>{post.title}<ArrowUpRight size={16}/></h3><p>{post.summary.slice(0,200)}</p><Badge kind="ai" mock={post.isMock}/></button></div>}
