import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';
import {indexConnections,hasProducer}from '../src/data/connections';import {indexFarms}from '../src/data/farms';import {adaptLegacy}from '../src/data/legacy';import {mergeUpdates}from '../src/data/updates';import {selectRecords}from '../src/data/taxonomy';import type{ArchiveSnapshot,Post}from '../src/data/types';import catalog from '../src/data/producer-catalog.json';import {searchLocal}from '../src/data/provider';
const make=(caption:string,id='test'):Post=>({id,caption,date:'2026-10-03',country:'국가 미분류',region:'',farmId:'',producerId:'',title:'test',summary:'',tags:[],isMock:false});
const snapshot=(posts:Post[]):ArchiveSnapshot=>({posts,farms:[],producers:[],issues:[],mode:'imported'});
const raw=JSON.parse(readFileSync(new URL('../public/archive_data.json',import.meta.url),'utf8'));const updates=JSON.parse(readFileSync(new URL('../public/archive_updates.json',import.meta.url),'utf8'));const before=indexFarms(mergeUpdates(adaptLegacy(raw,'./'),updates));const data=indexConnections(before);
test('different processing spellings and combined mentions remain distinct',()=>{const post=indexConnections(snapshot([make('커피의 와시드, natural, honey, 아나에어로빅, carbonic maceration을 비교했다.')])).posts[0];assert.deepEqual(post.processingIds,['washed','natural','honey','anaerobic','carbonic']);for(const quote of Object.values(post.processingEvidence||{}))assert.ok(post.caption.includes(quote));assert.equal(indexConnections(snapshot([make('허니 토스트와 내추럴 와인을 먹었다.')])).posts[0].processingIds?.length,0)});
test('matching person names retain separate identities and exclude artists',()=>{const a=indexConnections(snapshot([make('엘캄발라체 농장의 사무엘은 커피를 가공했다.'),make('사무엘 데겔로 Samuel Degelo는 에티오피아 커피 농부다.','other'),make('오스카 와일드와 디에고 리베라의 작품.','artist'),make('코르디예라 데 푸에고의 루이스는 커피를 가공했다.','luis')])).posts;assert.ok(hasProducer(a[0],'producer-samuel'));assert.ok(!hasProducer(a[1],'producer-samuel'));assert.ok(hasProducer(a[1],'producer-samuel-degelo'));assert.equal(a[2].producerIds?.length,0);assert.ok(!hasProducer(a[3],'producer-luis'))});
test('every catalog source quote and indexed quote comes from the preserved caption',()=>{for(const e of catalog.producers)for(const evidence of e.evidence){const p=data.posts.find(p=>p.id===evidence.postId)!;assert.ok(p.caption.includes(evidence.quote));assert.ok(hasProducer(p,e.id),e.id)}assert.equal(data.posts.length,before.posts.length);for(const p of data.posts){const old=before.posts.find(old=>old.id===p.id)!;assert.equal(p.caption,old.caption);assert.equal(p.sourceUrl,old.sourceUrl);assert.equal(p.imageUrl,old.imageUrl);for(const q of [...Object.values(p.processingEvidence||{}),...Object.values(p.producerEvidence||{})])assert.ok(p.caption.includes(q))}});
test('processing and producer filters intersect on the same post without inferring ownership',()=>{const records=indexConnections(snapshot([make('산타로사 농장주 라울의 커피와 워시드를 비교했다.','a'),make('산타로사 농장주 라울의 내추럴 커피.','b')])).posts;const f={country:'All',group:'All',topic:'All',recordYear:'All',untilYear:2026,sort:'recent' as const,processing:'washed',producer:'producer-raul-santa-rosa'};assert.deepEqual(selectRecords(records,f).map(p=>p.id),['a']);assert.equal(searchLocal('워시드',records).posts.length,1);assert.ok(searchLocal('탄산침용',[make('커피 carbonic maceration.')]).posts.length===1)});
